version: "3.8"

services:
  api-gateway:
    build: ./api-gateway-service
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - RUNNING_IN_DOCKER=true
      - JWT_SECRET=123456

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "9090:9090"
