global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8081']

  - job_name: 'circuit-breaker-service'
    static_configs:
      - targets: ['circuit-breaker-service:8080']
