version: "3.8"

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"

  service-registry:
    build: ./service-registry-service
    container_name: service-registry
    ports:
      - "8080:8080"
    depends_on:
      - consul
    environment:
      - RUNNING_IN_DOCKER=true
      - JWT_SECRET=123456
      - CONSUL_HTTP_ADDR=consul:8500

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - consul
    environment:
      - RUNNING_IN_DOCKER=true
      - JWT_SECRET=123456
      - CONSUL_HTTP_ADDR=consul:8500
      - DB_CONN=your_postgres_connection

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - consul
    environment:
      - RUNNING_IN_DOCKER=true
      - JWT_SECRET=123456
      - CONSUL_HTTP_ADDR=consul:8500
      - DB_CONN=your_postgres_connection
