services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
    - "8500:8500"
    - "8600:8600/udp"
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - consul
    environment:
      - RUNNING_IN_DOCKER=true
      - JWT_SECRET=123456
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
