version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  saga-synchronization:
    build: ./synchronization
    container_name: saga-synchronization
    ports:
      - "8083:8083"
    environment:
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - kafka
    restart: on-failure

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - saga-synchronization
    restart: on-failure

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    environment:
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - saga-synchronization
    restart: on-failure
